name: cloudflare

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 16 ]  # change the Node.js version to 16 here

    steps:
      - uses: actions/setup-node@v3  # update this action to use v3
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v2  # it's a good idea to use the latest stable version of checkout action too

      - name: Cache node_modules
        uses: actions/cache@v3  # assuming v3 is the latest stable version, if not adjust to the latest stable version
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles('**/yarn.lock') }}  # simplified the hashFiles input 

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd poddley_client
          yarn

      - name: Build
        run: |
          cd poddley_client
          yarn build
        env:
          NITRO_PRESET: cloudflare

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
