name: CI/CD Pipeline
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PODDLEY_DROPLET_IP }}
        username: ${{ secrets.PODDLEY_DROPLET_USER }}
        key: ${{ secrets.PODDLEY_SSH_KEY }}
        script: bash /path_to_script/deploy.sh